### ISSUE TITLE
Release Question

### ISSUE THREAD

**Issue by cambragol** [sean-gugler/u4remasteredA2#1]
Is the release file: u4remasteredA2_v100.zip
meant to be used for building from the source? Or is that a built version?

**Comment by sean-gugler** [comment]
It is a built version that already contains the fixes. Enjoy!

**Comment by cambragol** [comment]
Okay, then I must report that it is not working on 2 emulators I have tried so far.

I tried https://www.scullinsteel.com/apple//e# and AppleCommander.

Both boot from the program disk into a prompt, but from there, nothing.

**Comment by cambragol** [comment]
Sorry, Apple2Mac, not AppleCommander.

Typing any commands at the prompt fills the screen with "@" symbols.

**Comment by cambragol** [comment]
Tried a third emulator, which boots only into a command prompt, but also gives a 'file not found' message.

https://virtualconsoles.com/online-emulators/apple-ii/

**Comment by sean-gugler** [comment]
My mistake! The zip file was incorrect. I've updated it, please try it again now.

**Comment by sean-gugler** [comment]
Version 1.0.0 is now obsolete. Fixed in 1.0.1
