### ISSUE TITLE
Healer is always named Pendragon when he says Bye after blood donation

### ISSUE THREAD

**Issue by TeaRex73** [sean-gugler/u4remasteredA2#15]
Dear sean-gugler,

there is a bug in the healer routine "SHP5.s". The blood donation clobbers zp_index and leaves it at zero. Thus the game forgets which healer shop the player is in, and the guy who says good-bye is always called "Pendragon", i.e. the healer in shop number zero. You might want to fix this one too, I noticed it way back in the 80s and found the reason a few years back.

Thanks for all your effort!!

**Comment by sean-gugler** [comment]
Thanks for the detailed report! I'll look into this as soon as I can. Sounds like an easy fix.

**Comment by sean-gugler** [comment]
This is now fixed in release 1.2.8.
