### ISSUE TITLE
What was fixed?

### ISSUE THREAD

**Issue by Fenyx4** [sean-gugler/u4remasteredA2#2]
I dug around for a list but couldn't find it.

**Comment by sean-gugler** [comment]
Right now, you can find that list in the commit comment for the "fixed" branch.
https://github.com/sean-gugler/u4remasteredA2/commit/222d9c81cb61ccada393e31b91689b7cc5c26e9d

Eventually I will document them in this project's Wiki, similar to how I documented the C64 edition.
https://github.com/sean-gugler/u4remastered/wiki/Version_2_3_0

**Comment by Fenyx4** [comment]
Thank you!

**Comment by cambragol** [comment]
If you are looking for more bugs to fix, the about page for Threat of the Trinity lists all the bugs in DOS, including several new ones that were not widely or ever reported. Most are for DOS, but several are in Apple II as well.

https://cambragol.github.io/advent-of-the-trinity/about

**Comment by sean-gugler** [comment]
Sure, I'd love to review those once I'm done porting the "trainer" enhancements from MagerValp's C64 edition. Where might I find technical details on the issues and their fixes? The descriptions in that list are too brief to be actionable.

**Comment by cambragol** [comment]
Sorry, but that is as much detail as I recorded. I am not big on documentation. I can elaborate on them here if you wish. Fenyx4 might have made more detailed records for his Randomizer project as well.

**Comment by Fenyx4** [comment]
This is incomplete but I'll try to get it updated soon https://github.com/Fenyx4/U4DosRandomizer/blob/master/FIXES.md

I just tested it and the "being able to x-it the balloon while flying" bug that is in the last Apple II version I played is fixed. Nice!

**Comment by sean-gugler** [comment]
The list of fixes is now in the README.md file on the main branch.

All the fixes in the link from Fenyx4 above are present in version 1.1.0.
