### ISSUE TITLE
New Game hangs

### ISSUE THREAD

**Issue by cambragol** [sean-gugler/u4remasteredA2#3]
Starting a new game, in multiple online emulators, hangs at this screen of the new game sequence:

<img width="576" alt="Screen Shot 2021-06-19 at 14 07 14" src="https://user-images.githubusercontent.com/5019739/122631637-fc221380-d107-11eb-95a0-63b4263959b4.png">

**Comment by cambragol** [comment]
Also hangs in same place with Apple2Mac emulator.

**Comment by sean-gugler** [comment]
Alas, I see that also. I'm reviewing my messy dev branches, and I think I made a bad merge when I squashed the commits for publication.

Best hold off until I put version 1.0.1 up. I'm going to review my diffs very, very carefully.

**Comment by sean-gugler** [comment]
@cambragol Version 1.0.1 is now posted. Enjoy!

**Comment by cambragol** [comment]
Tested the new version and made it past this point. In game and everything looks smooth so far.

**Comment by Fenyx4** [comment]
cambragol beat me to it. I can also confirm that the new version gets past the hang point.

**Comment by cambragol** [comment]
Tested on multiple platforms, so I'll just close this then...
