### ISSUE TITLE
Can't enable "Fair Buy-back weapon at half price"

### ISSUE THREAD

**Issue by darrenjaneczek** [sean-gugler/u4remasteredA2#5]
Using the pre-build Apple ][ disk images, after setting the "Buy-back weapon at half price doesn't carry the hundreds place" option in the trainer, I found that maces still sell for 0G.

**Comment by sean-gugler** [comment]
Confirmed, I can reproduce this issue. Thank you for reporting! It will be fixed in the next release.

**Comment by sean-gugler** [comment]
Fixed in release 1.2.0
