### ISSUE TITLE
Mockingboard Support is broken on Apple IIgs

### ISSUE THREAD

**Issue by Dekkion42** [sean-gugler/u4remasteredA2#6]
This was broken from Origin. There is a Patch to make U4 with Mockingboard to work on the GS. 
I believe the core of the patch is written using apple basic.

As you are working with the source it would be great to have it work without the patch on the GS. 
(One U4 to rule them All :) Granted ProDos support will be AWESOME )
I have not tried running the patch with this version of U4

You can look into the SHK file on Windows using Ciderpress (perhaps others) 

Patch:
http://mirrors.apple2.org.za/ground.icaen.uiowa.edu/upl1999/Feb99/U4MBonGSv22.SHK
Generic Txt file:
http://mirrors.apple2.org.za/ground.icaen.uiowa.edu/upl1999/Feb99/U4MBonGSv22info.txt

Symptoms: Generally after selecting the slot for the Mockingboard it hangs, sometimes it will return to main menu but when you try and select J)ourney Onward or (Forgot I)Create party?) it Hangs 

Test Configuration: (This should apply to all IIGS regardless of configuration, Glories of a 30+ year old bug) 
Rom 1 with 1MB Apple memory card 
Phasor (Mockingboard Compatible) in slot 2 with the Control Panel set as My Card (Also Tried Slot 4 with Slot as MyCard)
CFFA in Slot 7

Thank you for all your hard work!

**Comment by sean-gugler** [comment]
Thanks for the suggestion! I'll take a look into that.

**Comment by sean-gugler** [comment]
Fixed, I hope. Can you please test it? I couldn't find a way to test it myself, but I replicated the patch verbatim, plus source code annotation for what it's doing.

**Comment by Dekkion42** [comment]
I will, machine torn down temporarily. Out of town most of tomorrow, Will work on Thursday for sure. Thank you!!!

**Comment by Dekkion42** [comment]
It WORKS!!! Thank you so much. This is very awesome.

**Comment by sean-gugler** [comment]
Excellent! Glad to hear it. If you or anyone are curious about the details of implementation, I've documented them in the wiki for this project.

https://github.com/sean-gugler/u4remasteredA2/wiki/Technical_Details#support-iigs-with-mockingboard-cards
