### ISSUE TITLE
How do I transfer save games from previous Ultima IV into Ultima IV Remastered ?

### ISSUE THREAD

**Issue by wyatt-wong** [sean-gugler/u4remasteredA2#7]
I copied the SAVE file from previous Ultima IV Britannia Disk into the Ultima IV Remastered Britannia Disk and overwrite the SAVE file. Then when I boot up Ultima IV Remastered and select Journey Onwards and load the save game from the Britannia disk, I got the error message of "NO ACTIVE GAME!". How to resolve it ?
<img width="1298" alt="Screen Shot 2021-10-01 at 2 30 06 AM" src="https://user-images.githubusercontent.com/10095648/135511053-78e56f6d-1cbe-4713-a1de-d0fee2264a87.png">

**Comment by sean-gugler** [comment]
One way is to boot up the Remastered game, but insert your previous Britannia disk at the prompt to load your old characters. Then switch disks to the new Britannia disk and press Q to quit-and-save onto that disk.

Another way is to copy the PRTY and ROST files. That's where the actual saved game data is. The file named SAVE is actually the sub-program that Ultima IV runs when your whole party dies, to "save" you from oblivion and return you to Britannia castle.

**Comment by wyatt-wong** [comment]
> One way is to boot up the Remastered game, but insert your previous Britannia disk at the prompt to load your old characters. Then switch disks to the new Britannia disk and press Q to quit-and-save onto that disk.
> 
> Another way is to copy the PRTY and ROST files. That's where the actual saved game data is. The file named SAVE is actually the sub-program that Ultima IV runs when your whole party dies, to "save" you from oblivion and return you to Britannia castle.

OK. I have copied PRTY and ROST files from the previous Ultima 4 Britannia Disk into Ultima 4 Remastered Britannia Disk and can successfully load the save games.
