### ISSUE TITLE
Chest Gold

### ISSUE THREAD

**Issue by smarinel** [sean-gugler/u4remasteredA2#8]
Hello! So I am trying to play this game for the first time on Apple II and have it running fine but when I get gold from a chest after combat it doesn't seem to add to my gold total? In fact my gold seems to go down sometimes? I don't really understand. I have only played the NES version a little before. This is using the latest build of the game.

**Comment by sean-gugler** [comment]
Thank you for the report! I confirm I see this bug also. It was not present in the retail edition, I introduced it by mistake with one of my patches. I will fix it for the next release.

**Comment by sean-gugler** [comment]
Fixed with version 1.2.6

**Comment by sean-gugler** [comment]
@smarinel  you can continue your saved game from an older version. Boot up the game from the new "u4program.do" and use your previous "u4britannia.do" disk and the gold bug will be fixed.
