### ISSUE TITLE
Mockingboard and IIGS

### ISSUE THREAD

**Issue by smarinel** [sean-gugler/u4remasteredA2#9]
Back again - the gold update is working well but I have tried the game out on my IIGS and found that trying to select the Mockingboard audio causes a crash. This apparently was a longstanding problem with IV and there was a patched version made at some point. 

I found some resources with the patch. Would it be possible to have a version of this build that worked with audio on the IIGS?

https://comp.sys.apple2.narkive.com/yGBIoDdA/ultima-mockingboards-on-each-of-the-apples

https://www.apple2.org.za/gswv/a2zine/Games/U4MB_Ultima4withMockingBoard_onGSv22info.txt

**Comment by sean-gugler** [comment]
Do you have an actual Mockingboard card in your IIGS? Support for the patch you mentioned was added already, see issue #6.

If you don't have a Mockingboard (or compatible device) you're out of luck. The native Ensoniq sound chip in the IIGS is not supported by any version of Ultima IV that I'm aware of.

**Comment by smarinel** [comment]
I do indeed in SLOT 4 and it works with Berzap but trying to activate it in U4 just causes everything to hang. Wasn't sure if that patch was included in the most recent program disk I downloaded with the money fix.

**Comment by smarinel** [comment]
For more details based on reading your previous solution - this is a ROM 3 machine with the card in Slot 4 and it set to MY CARD in the control panel.

**Comment by smarinel** [comment]
After reseating the card again in another slot it work works like it did on my IIE. Sorry for the confusion and posts.

**Comment by sean-gugler** [comment]
Glad to hear you got it working!

I would have expected it to work in Slot 4 though. If you ever move it back to slot 4 and find that U4 still does not work but Berzap does, I'll dig into what Berzap is doing differently so I can fix it in U4.
